const CalculatorTypes = {
  APPEND: "APPEND",
  CLEAR: "CLEAR",
  CLEAR_ENTRY: "CLEAR_ENTRY",
  BACK_SPACE: "BACK_SPACE",
  TWO_ELEMENTS: "TWO_ELEMENTS",
  PLUS_MINUS: "PLUS_MINUS",
  PERCENT: "PERCENT",
  RECIPROCAL: "RECIPROCAL",
  SQUARE: "SQUARE",
  SQUAREROOT: "SQUAREROOT",
  EQUALS_TO: "EQUALS_TO",
};

export default CalculatorTypes;
